# Generated by Django 3.2.8 on 2021-10-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_exercise_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_session',
            name='measurement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise_session',
            name='type',
            field=models.CharField(choices=[('Walking', 'WALKING'), ('Running', 'RUNNING'), ('Squats', 'SQUATS'), ('Push-ups', 'PUSH-UPS'), ('Jogging', 'JOGGING'), ('Swimming', 'SWIMMING'), ('Dancing', 'DANCING')], default='select exercise type', max_length=20),
        ),
    ]
