# Generated by Django 3.2.8 on 2021-10-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20211025_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_session',
            name='measurement',
            field=models.CharField(max_length=20),
        ),
    ]
