# Generated by Django 3.2.8 on 2021-10-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_exercise_session_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise_session',
            name='additonal_notes',
        ),
        migrations.RemoveField(
            model_name='exercise_session',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exercise_session',
            name='measurement',
        ),
    ]
